export const COPY = {
  app: {
    name: 'Tracer',
    tagline: 'The world leaves traces. Find yours.',
    taglineSub: 'Decode the city. Find what others miss.',
  },
  trace: {
    singular: 'trace',
    plural: 'traces',
    briefing: 'Trace briefing',
    crack: 'Crack the trace',
    active: 'Trace active',
    solved: 'Trace solved',
    failed: 'Trace failed',
    reveal: 'Reveal trace',
    timeLeft: 'Time remaining',
    expired: 'Window closed',
    attemptsLeft: 'attempts left',
    locationClassified: 'Location classified',
    submitProof: 'Submit proof',
    getCloser: 'Get closer',
  },
  submit: {
    cta: 'Submit proof',
    capturing: 'Capturing proof...',
    verifying: 'Verifying location...',
    verified: 'Location confirmed',
    rejected: 'Not close enough',
    communityReview: 'Under review',
  },
  feed: {
    title: 'Field intel',
    empty: 'No traces found yet today.',
    vote: {
      valid: 'Legit',
      invalid: 'Fake',
      unsure: 'Unsure',
    },
  },
  map: {
    title: 'Hunt',
    traceHunt: 'Trace hunt',
    territory: 'My territory',
    ghostTrail: 'Ghost trail',
    nearby: 'Nearby',
  },
  social: {
    taunt: 'Taunt',
    tauntSent: 'Taunt sent',
    tauntReceived: 'You\'ve been taunted',
    liveRace: 'Live race',
    rescue: 'Rescue',
    rescueSent: 'Rescue sent',
    bountyBoard: 'Bounty board',
    territory: 'Territory',
    ghostTrail: 'Ghost trail',
  },
  events: {
    title: 'Arena',
    liveRace: 'Live race',
    bountyBoard: 'Bounty board',
    territory: 'Territory war',
    legendary: 'Critical trace',
  },
  profile: {
    title: 'Agent',
    level: {
      recruit: 'Recruit',
      agent: 'Agent',
      operative: 'Operative',
      fieldAgent: 'Field agent',
      handler: 'Handler',
      legend: 'Legend',
    },
    streak: 'Active run',
    squad: 'Squad',
    archive: 'Archive',
    solvedCount: 'traces cracked',
  },
  onboarding: {
    title: 'TRACER',
    tagline: 'The world leaves traces. Find yours.',
    subtitle: 'Decode clues. Find the place. Leave your trace.',
    cta: 'Send access link',
    signIn: 'Already a Tracer? Sign in',
    preview: 'Preview the app →',
    arenaTitle: 'Choose your arena.',
    arenaSub: 'Compete globally or find your crew.',
    globalArena: 'The World',
    globalArenaSub: 'Trace against everyone, everywhere',
    privateArena: 'Private arena',
    privateCode: 'Enter invite code',
    continueBtn: 'Begin your run →',
  },
  notifications: {
    traceNearby: '🔴 A trace appeared {distance}m away. Crack it.',
    traceExpiring: '⏰ Trace closing. Last chance.',
    streakWarning: '🔥 Your run is at risk.',
    taunted: '⚔️ {name} taunted you. {time} to beat their time.',
    rescued: '🤝 {name} sent you a rescue hint.',
    rescueSuccess: '✓ {name} cracked it. Your run continues.',
    rescueFailed: '✗ {name} couldn\'t crack it. Run broken.',
    territoryLost: '🚩 {name} took your territory in {zone}.',
    bounty: '💰 {xp} XP bounty posted on a trace near you.',
    liveRace: '⚡ {name} challenged you to a live race. Now.',
  },
} as const;
