export const COPY = {
  app: {
    name: 'Dare',
    tagline: 'The city dares you.',
    taglineSub: 'One dare. Every day. No excuses.',
  },
  challenge: {
    singular: 'dare',
    plural: 'dares',
    briefing: 'Mission briefing',
    accept: 'Accept the dare',
    accepted: 'Mission active',
    complete: 'Mission complete',
    missed: 'Dare missed',
    reveal: 'Reveal your dare',
    timeLeft: 'Time on mission',
    expired: 'Window closed',
  },
  submit: {
    cta: 'Submit proof',
    capturing: 'Capturing proof...',
    verifying: 'Analysing proof...',
    verified: 'Proof confirmed',
    rejected: 'Proof rejected',
    communityReview: 'Under review',
  },
  feed: {
    title: 'City intel',
    empty: 'No proof submitted yet today.',
    vote: {
      valid: 'Legit',
      invalid: 'Fake',
      unsure: 'Unsure',
    },
  },
  map: {
    title: 'Field ops',
    hunt: 'Hunt',
    territory: 'My territory',
    plant: 'Plant a flag',
    found: 'I found it',
  },
  events: {
    title: 'Arena',
    duel: 'Head to head',
    tournament: 'City war',
    legendary: 'Critical dare',
    chainUnlock: 'Classified',
    relay: 'Chain',
    parallelLives: 'Parallel',
    takeover: 'Takeover',
  },
  profile: {
    title: 'Agent',
    level: {
      wanderer: 'Recruit',
      scout: 'Agent',
      explorer: 'Operative',
      chronicler: 'Field agent',
      keeper: 'Handler',
      legend: 'Legend',
    },
    streak: 'Active run',
    crew: 'Squad',
    archive: 'Archive',
  },
  onboarding: {
    welcome: 'Are you brave enough?',
    subtitle: 'A dare drops in your city every day.\nYou have 2 hours. No excuses.',
    cta: 'Accept the challenge',
    signIn: 'Already an agent?',
  },
  notifications: {
    challengeDrop: "🎯 Your dare just dropped. 2 hours. Go.",
    reminder: "⏰ Dare is still live. Don't miss it.",
    streakWarning: "🔥 Your run is at risk. Submit before midnight.",
    ceremony: "🏆 Mission results are in.",
    legendary: "⚡ CRITICAL DARE. 30 minutes. Now.",
    duel: "⚔️ You've been challenged to a head to head.",
    parallelLives: "🌍 Someone just completed your dare in another city.",
    expedition: "🚩 Your flag was found.",
  },
} as const;
